### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by satra** [ReproNim/simple_workflow#15]
although we don't have a Dockerfile and the docker option wasn't targeted at version 1, it would be good to include one, so that our reviewer, who comes from a non imaging background, can actually re-execute the workflow.

@dnkennedy and @yarikoptic - as part of a revision how about we make docker integral and have people use it to repeat/reproduce.

**Comment by yarikoptic** [comment]
I am confused...
https://github.com/ReproNim/simple_workflow/blob/master/README.md#within-docker

Of cause we could pregenerate one dockerfile for a specific version of that would be of help - would it be?

**Comment by satra** [comment]
did you see @khinsen comment on the paper that he couldn't run the dockerfile generator script. is the script universal (i.e., osx, any linux), and does the script itself have any dependencies other than docker? (https://f1000research.com/articles/6-124/v1 - comments at the bottom)

@khinsen - just to be sure did you try running docker directly as instructed here:  https://github.com/ReproNim/simple_workflow/blob/master/README.md#run-the-demo-1

**Comment by khinsen** [comment]
What I tried is exactly this command line:

```
./Simple_Prep_docker jessie 20150306T060524Z
```

Since the complicated part seems to be the generation of the Dockerfile for a specific version of NeuroDebian, it would probably indeed help to supply one specific Dockerfile explicitly. That's also more in line with the idea of reproducibility - supply as much information about the specific environment you used.

**Comment by yarikoptic** [comment]
Thank you @khinsen! Indeed we need to make helper script more portable , and provide a sample dockerfile... Will do that later today and let you know

**Comment by yarikoptic** [comment]
while on the run could quickly pre-generate one and pushed directly into master:  https://github.com/ReproNim/simple_workflow/blob/master/Dockerfile   -- please give it a try

**Comment by khinsen** [comment]
I downloaded that file and executed the line
```bash
docker build -t repronim:example -f Dockerfile .
```
which I adapted from the end of the `Simple_Prep_docker` script. That took a while but worked perfectly well.

Then I continued at the end of `README.md`, executing the command

```bash
docker run -it --rm repronim:simple_prep_USER_jessie_20150306T060524Z /bin/bash -c '
  . setup_environment;
  cd simple_workflow-master
  && python run_demo_workflow.py --key 11an55u9t2TAf0EV2pHN0vOd8Ww2Gie-tHp9xGULh_dA
  && python check_output.py'
```

by copy-pasting these lines into a terminal window and editing the name of the docker image. Error message:

```
IN setup_environments
/bin/bash: -c: line 3: syntax error near unexpected token `&&'
/bin/bash: -c: line 3: `  && python run_demo_workflow.py --key 11an55u9t2TAf0EV2pHN0vOd8Ww2Gie-tHp9xGULh_dA'
```

Knowing about the fragility of shell one-liners, I then tried again, carefully copying everything into a single line:

```bash
docker run -it --rm repronim:example /bin/bash -c ' . setup_environment; cd simple_workflow-master && python run_demo_workflow.py --key 11an55u9t2TAf0EV2pHN0vOd8Ww2Gie-tHp9xGULh_dA && python check_output.py'
```

That seems to work. It's been running for a few hours and then stopped without anything looking like an error message.

However, the numerical results seem be off. This is the final comparison I get:

```
Outputs are not close enough. Printing difference
                   Background_volume  Background_voxels  \
AnnArbor_sub16960         487.200019              406.0
AnnArbor_sub20317        -114.799998              -82.0
AnnArbor_sub38614         -46.199999              -33.0
AnnArbor_sub46727         -34.999999              -25.0
AnnArbor_sub49687          71.399999               51.0
AnnArbor_sub82334          67.199999               48.0
AnnArbor_sub86367        -111.999998              -80.0
AnnArbor_sub87745          -1.400000               -1.0
AnnArbor_sub96621         -16.800000              -12.0
NewYork_sub20732           81.000000               81.0
NewYork_sub26267         -111.000000             -111.0
NewYork_sub28795          220.000000              220.0
NewYork_sub31671           83.000000               83.0
NewYork_sub44979           93.000000               93.0
NewYork_sub59589         -463.000000             -463.0
NewYork_sub61001         -219.000000             -219.0
NewYork_sub61241           18.000000               18.0
NewYork_sub66941          595.000000              595.0
NewYork_sub70752          -57.000000              -57.0
NewYork_sub73490           26.000000               26.0
NewYork_sub84978          -41.000000              -41.0
NewYork_sub88286          135.000000              135.0
NewYork_sub93975         -133.000000             -133.0
NewYork_sub96705            0.000000                0.0

                   Left-Accumbens-area_volume  Left-Accumbens-area_voxels  \
AnnArbor_sub16960                   19.200001                        16.0
AnnArbor_sub20317                    5.600000                         4.0
AnnArbor_sub38614                  -72.799999                       -52.0
AnnArbor_sub46727                   -5.600000                        -4.0
AnnArbor_sub49687                    7.000000                         5.0
AnnArbor_sub82334                   -5.600000                        -4.0
AnnArbor_sub86367                  -19.600000                       -14.0
AnnArbor_sub87745                    0.000000                         0.0
AnnArbor_sub96621                   18.200000                        13.0
NewYork_sub20732                   -35.000000                       -35.0
NewYork_sub26267                   -10.000000                       -10.0
NewYork_sub28795                   -59.000000                       -59.0
NewYork_sub31671                   -22.000000                       -22.0
NewYork_sub44979                    -9.000000                        -9.0
NewYork_sub59589                    17.000000                        17.0
NewYork_sub61001                   -28.000000                       -28.0
NewYork_sub61241                    -6.000000                        -6.0
NewYork_sub66941                    71.000000                        71.0
NewYork_sub70752                   -15.000000                       -15.0
NewYork_sub73490                   -33.000000                       -33.0
NewYork_sub84978                    12.000000                        12.0
NewYork_sub88286                    -1.000000                        -1.0
NewYork_sub93975                    51.000000                        51.0
NewYork_sub96705                     0.000000                         0.0

                   Left-Amygdala_volume  Left-Amygdala_voxels  \
AnnArbor_sub16960             13.200001                  11.0
AnnArbor_sub20317             47.599999                  34.0
AnnArbor_sub38614            -44.799999                 -32.0
AnnArbor_sub46727             28.000000                  20.0
AnnArbor_sub49687            -89.599998                 -64.0
AnnArbor_sub82334            -36.399999                 -26.0
AnnArbor_sub86367            -18.200000                 -13.0
AnnArbor_sub87745              0.000000                   0.0
AnnArbor_sub96621             -8.400000                  -6.0
NewYork_sub20732              12.000000                  12.0
NewYork_sub26267             -93.000000                 -93.0
NewYork_sub28795            -106.000000                -106.0
NewYork_sub31671             -58.000000                 -58.0
NewYork_sub44979               3.000000                   3.0
NewYork_sub59589               7.000000                   7.0
NewYork_sub61001              15.000000                  15.0
NewYork_sub61241              -4.000000                  -4.0
NewYork_sub66941              -5.000000                  -5.0
NewYork_sub70752              -7.000000                  -7.0
NewYork_sub73490               5.000000                   5.0
NewYork_sub84978             -12.000000                 -12.0
NewYork_sub88286              -6.000000                  -6.0
NewYork_sub93975              -6.000000                  -6.0
NewYork_sub96705               0.000000                   0.0

                   Left-Caudate_volume  Left-Caudate_voxels  \
AnnArbor_sub16960          -540.000021               -450.0
AnnArbor_sub20317            -2.800000                 -2.0
AnnArbor_sub38614            69.999999                 50.0
AnnArbor_sub46727            53.199999                 38.0
AnnArbor_sub49687             8.400000                  6.0
AnnArbor_sub82334             1.400000                  1.0
AnnArbor_sub86367           -28.000000                -20.0
AnnArbor_sub87745             1.400000                  1.0
AnnArbor_sub96621             4.200000                  3.0
NewYork_sub20732             -1.000000                 -1.0
NewYork_sub26267             10.000000                 10.0
NewYork_sub28795             54.000000                 54.0
NewYork_sub31671             23.000000                 23.0
NewYork_sub44979             44.000000                 44.0
NewYork_sub59589             23.000000                 23.0
NewYork_sub61001             33.000000                 33.0
NewYork_sub61241             13.000000                 13.0
NewYork_sub66941            -26.000000                -26.0
NewYork_sub70752             17.000000                 17.0
NewYork_sub73490              6.000000                  6.0
NewYork_sub84978            -10.000000                -10.0
NewYork_sub88286            -16.000000                -16.0
NewYork_sub93975            276.000000                276.0
NewYork_sub96705              0.000000                  0.0

                   Left-Hippocampus_volume  Left-Hippocampus_voxels  \
AnnArbor_sub16960                -8.400000                     -7.0
AnnArbor_sub20317               -23.800000                    -17.0
AnnArbor_sub38614               -11.200000                     -8.0
AnnArbor_sub46727               -32.199999                    -23.0
AnnArbor_sub49687               158.199997                    113.0
AnnArbor_sub82334                28.000000                     20.0
AnnArbor_sub86367                29.399999                     21.0
AnnArbor_sub87745                 0.000000                      0.0
AnnArbor_sub96621                16.800000                     12.0
NewYork_sub20732                  8.000000                      8.0
NewYork_sub26267                121.000000                    121.0
NewYork_sub28795                -21.000000                    -21.0
NewYork_sub31671                -20.000000                    -20.0
NewYork_sub44979                 16.000000                     16.0
NewYork_sub59589                 19.000000                     19.0
NewYork_sub61001                 26.000000                     26.0
NewYork_sub61241                -18.000000                    -18.0
NewYork_sub66941                -34.000000                    -34.0
NewYork_sub70752                -27.000000                    -27.0
NewYork_sub73490                -12.000000                    -12.0
NewYork_sub84978                -92.000000                    -92.0
NewYork_sub88286                 11.000000                     11.0
NewYork_sub93975                 -8.000000                     -8.0
NewYork_sub96705                  0.000000                      0.0

                       ...       Right-Putamen_volume  Right-Putamen_voxels  \
AnnArbor_sub16960      ...                 -27.600001                 -23.0
AnnArbor_sub20317      ...                  65.799999                  47.0
AnnArbor_sub38614      ...                 198.799997                 142.0
AnnArbor_sub46727      ...                 -23.800000                 -17.0
AnnArbor_sub49687      ...                -141.399998                -101.0
AnnArbor_sub82334      ...                 -95.199998                 -68.0
AnnArbor_sub86367      ...                  -7.000000                  -5.0
AnnArbor_sub87745      ...                   0.000000                   0.0
AnnArbor_sub96621      ...                 -60.199999                 -43.0
NewYork_sub20732       ...                  42.000000                  42.0
NewYork_sub26267       ...                  32.000000                  32.0
NewYork_sub28795       ...                 -74.000000                 -74.0
NewYork_sub31671       ...                  47.000000                  47.0
NewYork_sub44979       ...                -104.000000                -104.0
NewYork_sub59589       ...                 -89.000000                 -89.0
NewYork_sub61001       ...                  21.000000                  21.0
NewYork_sub61241       ...                -112.000000                -112.0
NewYork_sub66941       ...                 -48.000000                 -48.0
NewYork_sub70752       ...                   0.000000                   0.0
NewYork_sub73490       ...                  32.000000                  32.0
NewYork_sub84978       ...                 -67.000000                 -67.0
NewYork_sub88286       ...                  58.000000                  58.0
NewYork_sub93975       ...                   0.000000                   0.0
NewYork_sub96705       ...                   0.000000                   0.0

                   Right-Thalamus-Proper_volume  Right-Thalamus-Proper_voxels  \
AnnArbor_sub16960                     -6.000000                          -5.0
AnnArbor_sub20317                    -29.399999                         -21.0
AnnArbor_sub38614                    -54.599999                         -39.0
AnnArbor_sub46727                     -7.000000                          -5.0
AnnArbor_sub49687                      7.000000                           5.0
AnnArbor_sub82334                      9.800000                           7.0
AnnArbor_sub86367                      9.800000                           7.0
AnnArbor_sub87745                      0.000000                           0.0
AnnArbor_sub96621                    -11.200000                          -8.0
NewYork_sub20732                     -76.000000                         -76.0
NewYork_sub26267                     -13.000000                         -13.0
NewYork_sub28795                      37.000000                          37.0
NewYork_sub31671                      -5.000000                          -5.0
NewYork_sub44979                     -11.000000                         -11.0
NewYork_sub59589                      32.000000                          32.0
NewYork_sub61001                     178.000000                         178.0
NewYork_sub61241                      16.000000                          16.0
NewYork_sub66941                     -14.000000                         -14.0
NewYork_sub70752                    -114.000000                        -114.0
NewYork_sub73490                     -11.000000                         -11.0
NewYork_sub84978                     -30.000000                         -30.0
NewYork_sub88286                      24.000000                          24.0
NewYork_sub93975                      52.000000                          52.0
NewYork_sub96705                       0.000000                           0.0

                   csf_volume  csf_voxels  gray_volume  gray_voxels  \
AnnArbor_sub16960  -18.000000       -15.0       3.6250          3.0
AnnArbor_sub20317    5.593750         4.0      -1.3750         -1.0
AnnArbor_sub38614    0.000000         0.0       0.0000          0.0
AnnArbor_sub46727  -29.406250       -21.0       8.3750          6.0
AnnArbor_sub49687   21.000000        15.0       0.0000          0.0
AnnArbor_sub82334  -14.000000       -10.0       0.0000          0.0
AnnArbor_sub86367   -9.796875        -7.0      -8.3750         -6.0
AnnArbor_sub87745    1.406250         1.0     -11.1875         -8.0
AnnArbor_sub96621   12.593750         9.0      -2.7500         -2.0
NewYork_sub20732     3.000000         3.0       0.0000          0.0
NewYork_sub26267     7.000000         7.0       6.0000          6.0
NewYork_sub28795    -4.000000        -4.0       6.0000          6.0
NewYork_sub31671    -4.000000        -4.0       7.0000          7.0
NewYork_sub44979     6.000000         6.0      -1.0000         -1.0
NewYork_sub59589     0.000000         0.0       0.0000          0.0
NewYork_sub61001     0.000000         0.0      -1.0000         -1.0
NewYork_sub61241     3.000000         3.0       7.0000          7.0
NewYork_sub66941     0.000000         0.0       0.0000          0.0
NewYork_sub70752     0.000000         0.0       0.0000          0.0
NewYork_sub73490    -3.000000        -3.0       3.0000          3.0
NewYork_sub84978     0.000000         0.0       0.0000          0.0
NewYork_sub88286     0.000000         0.0       0.0000          0.0
NewYork_sub93975     3.000000         3.0       1.0000          1.0
NewYork_sub96705    -9.500000       -12.0       0.0000          0.0

                   white_volume  white_voxels
AnnArbor_sub16960      14.40625          12.0
AnnArbor_sub20317      -4.18750          -3.0
AnnArbor_sub38614       0.00000           0.0
AnnArbor_sub46727      21.00000          15.0
AnnArbor_sub49687     -21.00000         -15.0
AnnArbor_sub82334      14.00000          10.0
AnnArbor_sub86367      18.18750          13.0
AnnArbor_sub87745       9.81250           7.0
AnnArbor_sub96621      -9.81250          -7.0
NewYork_sub20732       -3.00000          -3.0
NewYork_sub26267      -13.00000         -13.0
NewYork_sub28795       -2.00000          -2.0
NewYork_sub31671       -3.00000          -3.0
NewYork_sub44979       -5.00000          -5.0
NewYork_sub59589        0.00000           0.0
NewYork_sub61001        1.00000           1.0
NewYork_sub61241      -10.00000         -10.0
NewYork_sub66941        0.00000           0.0
NewYork_sub70752        0.00000           0.0
NewYork_sub73490        0.00000           0.0
NewYork_sub84978        0.00000           0.0
NewYork_sub88286        0.00000           0.0
NewYork_sub93975       -4.00000          -4.0
NewYork_sub96705        9.50000          12.0

[24 rows x 36 columns]
Original platform: Linux-3.2.0-98-virtual-x86_64-with-debian-wheezy-sid
Original FSL version: 5.0.9
Current platform: Linux-4.9.8-moby-x86_64-with-debian-8.7
Current FSL version: 5.0.8
```

**Comment by dnkennedy** [comment]
Thanks @khinsen for looking at this.  Thanks @satra and @yarikoptic for preparing the Docker. To first approximation, the differences @khinsen finds in that run is 'expected' as the operating system and FSL version of the Docker is slightly different than the AMI reference run.  Which is sort of the point: to get exact similarity, one would need to run on the exact same platform/software version as the original.

A question for @yarikoptic , however, is if the Docker could have been created with FSL 5.0.9, to at least be a little potentially more similar to the reference run? I think I've tried this separately, and am not sure that any of the FSL tools that are used here change between those FSL releases, thus I suspect these small voxel differences are due to the OS variance.

**Comment by khinsen** [comment]
@dnkennedy If you can't adapt the Docker image to the reference run, how about doing the reference run with the Docker image?

**Comment by satra** [comment]
@khinsen, @yarikoptic, and @dnkennedy - in response to the reviews and comments here, we have updated the repo to use docker as the reference and revised the setup. 

details here:
https://github.com/ReproNim/simple_workflow/blob/master/README.md

once comparative outputs are stored, i will cut a release to contain the code and results. closing this issue for now.

**Comment by khinsen** [comment]
I did a quick test under macOS. No problem with downloading the docker image, but the first example crashes:
```
docker run -it --rm -v $PWD/output:/opt/repronim/simple_workflow/scripts/output repronim/simple_workflow:latest run_demo_workflow.py --key 11an55u9t2TAf0EV2pHN0vOd8Ww2Gie-tHp9xGULh_dA -n 1
```
output:
``` 
Added workflow for: AnnArbor_sub16960
170420-14:31:17,807 workflow INFO:
	 ['check', 'execution', 'logging']
170420-14:31:17,841 workflow INFO:
	 Running in parallel.
170420-14:31:17,846 workflow INFO:
	 Executing: download_url ID: 0
170420-14:31:17,853 workflow INFO:
	 Executing node download_url in dir: /opt/repronim/simple_workflow/scripts/output/metaflow/AnnArbor_sub16960/download_url
170420-14:31:18,471 workflow ERROR:
	 ['Node download_url failed to run on host 0fd4b3a9a572.']
170420-14:31:18,473 workflow INFO:
	 Saving crash info to /opt/repronim/simple_workflow/scripts/output/crash-20170420-143118-root-download_url-b2335aee-a1bf-49a6-845c-7d6437cc4612.pklz
170420-14:31:18,473 workflow INFO:
	 Traceback (most recent call last):
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 49, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 496, in _run_interface
    raise out
ConnectionError: (MaxRetryError('None: Max retries exceeded with url: /ir/ (Caused by None)',), '\nInterface Function failed to run.')

170420-14:31:18,485 workflow INFO:
	 ***********************************
170420-14:31:18,485 workflow ERROR:
	 could not run node: metaflow.AnnArbor_sub16960.download_url
170420-14:31:18,485 workflow INFO:
	 crashfile: /opt/repronim/simple_workflow/scripts/output/crash-20170420-143118-root-download_url-b2335aee-a1bf-49a6-845c-7d6437cc4612.pklz
170420-14:31:18,485 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "run_demo_workflow.py", line 218, in <module>
    meta_wf.run(args.plugin)
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 597, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 274, in run
    report_nodes_not_run(notrun)
  File "/opt/repronim/simple_workflow/miniconda/envs/bh_demo/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 95, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details
```

**Comment by satra** [comment]
@khinsen - thank you for the feedback. we will look into it. seems like the data store cannot be reached for some reason.

@dnkennedy, @chaselgrove - are there IP filters or blocks in place for NITRC-IR? and should we consider multiple locations for the data?

**Comment by khinsen** [comment]
@satra If it's a network problem, let me add that I did my test in a plain WiFi network without any proxy or firewall that could interfere. I used the latest Docker for macOS (updated yesterday for the occasion) and macOS 10.11.

**Comment by yarikoptic** [comment]
Fwiw. If data would be present from multiple locations, and placed under git annex/datalad - should all work out magically
